Vagrant::Config.run do |config|
  config.vm.box = "ubuntu-1204-i386"
  config.vm.box_url = "http://vagrant.sensuapp.org/ubuntu-1204-i386.box"

  config.vm.customize [
    "modifyvm", :id,
    "--name", "Recognizer",
    "--memory", "512"
  ]

  config.vm.provision :shell, :inline => "gem install chef -v 10.12.0 --no-rdoc --no-ri"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe("rabbitmq")
    chef.add_recipe("recognizer")
  end
end
